### ISSUE TITLE
Feat: 일반 추천 API를 구현한다.

### ISSUE THREAD

**Issue by HoyeongJeon** [KUSITMS-30th-TEAM-C/backend#64]
### 📝 Description

- 일반 추천 API를 구현합니다.

---

### 📝 Todo

- [x] 클라이언트에게 활동을 전달한다.
- [x] 클라이언트가 선택한 활동을 저장한다.
- [x] 활동 선택 시 title, contet를 함께 반환한다. 
- [ ] 활동 추천 스웨거를 작성한다.
