### ISSUE TITLE
Chore: CI/CD 스크립트를 작성하고 배포를 진행한다.

### ISSUE THREAD

**Issue by HoyeongJeon** [KUSITMS-30th-TEAM-C/backend#8]
### 📝 Description

- CI/CD 스크립트를 작성합니다.
- CI/CD 스크립트를 통해 배포를 자동화합니다.
---

### 📝 Todo

- [x] CI/CD 스크립트를 작성한다.
- [x] CI 스크립트를 통해 Docker Image를 Docker Hub에 업로드한다.
- [x] CD 스크립트에 따라 서버에 애플리케이션을 자동배포한다.
